package main

import (
	"github.com/kosovo21/hello-go/basic"
	"github.com/kosovo21/hello-go/exercise"
	"github.com/kosovo21/hello-go/flow"
	"github.com/kosovo21/hello-go/more"
)

func main() {
	basic.Hello()
	basic.Package()
	basic.Import()
	basic.Export()
	basic.Functions()
	basic.MultiResult()
	basic.NamedResult()
	basic.Variables()
	basic.VarInit()
	basic.ShortVar()
	basic.BasicTypes()
	basic.DefaultValue()
	basic.TypeConvert()
	basic.TypeInterface()
	basic.Constant()
	basic.NumericConstant()

	flow.For()
	flow.ForAsWhile()
	// flow.Forever()
	flow.If()
	flow.IfShort()
	flow.IfElse()
	exercise.Loop()
	flow.Switch()
	flow.SwitchOrder()
	flow.SwitchNoCondition()
	flow.Defer()
	flow.DeferStack()

	more.Pointer()
	more.Struct()
	more.StructField()
	more.StructPointer()
	more.StructLiteral()
	more.Array()
	more.Slices()
	more.SlicePointer()
	more.SliceLiteral()
	more.SliceDefault()
	more.SliceLenAndCap()
	more.SliceNil()
	more.SliceMake()
	more.SliceOfSlice()
	more.SliceAppend()
	more.Range()
	more.RangeSimple()
	exercise.Slice()
	more.Map()
	more.MapLiteral()
	more.MapAction()
	more.FunctionValue()
	more.FunctionClosure()
	more.FunctionFibonacci()
}
